#!/usr/bin/python
"""
copyright (c) 2010-2012, Gabriel A. Weaver, Department of Computer
Science at Dartmouth College. <gabriel.a.l.weaver@gmail.com>

This file is part of XUTools, Python Distribution.

This code is free software:  you can redistribute                
it and/or modify it under the terms of the GNU General Public                   
License as published by the Free Software Foundation, either version            
3 of the License, or (at your option) any later version.                        
                                                                                
XUTools is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.
                                                                                
You should have received a copy of the GNU General Public License               
along with this program.  If not, see http://www.gnu.org/licenses/
"""
import codecs
from pyparsing import *
from xutools.tools import XUDiff as XUD
import optparse
import sys

p = optparse.OptionParser()
p.add_option("-f", "--outfields", dest="output_field_names" )
p.add_option("-p", "--comp_field", dest="comparison_field" )
p.add_option("-c", "--cost_fn", dest="cost_fn_name" )
(options, args) = p.parse_args()

if ( len(args) < 3 ):
    print "Usage:  xudiff [ --outfields <field1,...,fieldN>] [--comp_field <field>] [ --cost_fn <cost_fn> ] <xpath> <file1> <file2>"
    sys.exit(-1)

xupath = args[0]
file_paths = args[1:]
XUD.xudiff_main( xupath, file_paths, options.output_field_names, options.comparison_field, options.cost_fn_name )

