#!/usr/bin/python
"""
copyright (c) 2010-2012, Gabriel A. Weaver, Department of Computer
Science at Dartmouth College. <gabriel.a.l.weaver@gmail.com>

This file is part of XUTools, Python Distribution.

This code is free software:  you can redistribute                
it and/or modify it under the terms of the GNU General Public                   
License as published by the Free Software Foundation, either version            
3 of the License, or (at your option) any later version.                        
                                                                                
XUTools is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.
                                                                                
You should have received a copy of the GNU General Public License               
along with this program.  If not, see http://www.gnu.org/licenses/
"""
import codecs
from xutools.corpus import CorpusElement
from xutools.grammar.pyparsing.BuiltinGrammar import BuiltinGrammar
from xutools.tools import XUWc
import optparse
import xutools.parsers
import sys

p = optparse.OptionParser()
p.add_option("-a", "--count", dest="count_unit", default=None)
p.add_option("-c", "--container", dest="container_unit", default=BuiltinGrammar.FILE)
(options, args) = p.parse_args()

if ( len(args) < 2 ):
    print "Usage xuwc [ --count <count_unit> | --container <container_unit> ] <xupath> <files>+"
    sys.exit(0)

xupath = args[0]
file_paths = args[1:]
count_unit = options.count_unit
container_unit = options.container_unit
label_path_delimiter = ":"

if None == count_unit:
    xupath_pcs = xupath.split("/")
    count_unit_idx = len(xupath_pcs) - 1
    count_unit = xupath_pcs[count_unit_idx]

attribute_names = [ CorpusElement.LABEL_PATH,\
                        CorpusElement.LANGUAGE_NAME_PATH,\
                        CorpusElement.TEXT ]
element_equality_fields = attribute_names
xuwc = XUWc.create(xupath, file_paths, element_equality_fields, count_unit, container_unit, label_path_delimiter)
results = xuwc.output()
print "\n".join(results)
