.\" Process this file with 
.\" groff -man -Tascii xuwc.1
.\"
.TH XUWC 1 "June 2013" XUTools "User Manuals"
.SH NAME 
xuwc \- Count the number of strings in the language of a grammar production

.SH SYNOPSIS
.B  xuwc 
.B [ 
.I --count 
.B ]
.B [ 
.I --container
.B ]
.I xupath
.I file
.B ...

.SH DESCRIPTION
xuwc(1) 
generalizes 
.BR wc(1) 
to count the number of strings in the language
of an xupath.  

Traditional 
.BR wc(1) 
counts the number of words, lines, characters, or
bytes contained in each input file or standard input.  

xuwc(1) generalizes 
.BR wc(1) 
to count strings in the language of an xupath and to report those
counts relative to language-specific contexts.  When no options are
specified,
.BR xuwc(1) 
will count the number of matches to the xupath within the file.  

All files are processed in the order specified.

.SH OPTIONS
.IP --count
The production references that we should count.  By default, this is
the final step in the provided xupath.  However, this may also be set
to builtin:byte, builtin:character, builtin:word, or builtin:line.  
We have not yet tested these tools on Unicode.

.IP --container
The context in which to report counts.  By default, this is the file.
However, it could be any step of the xupath.  If one uses the count
option, however, the container unit should be set to the final component of
the xupath

.SH FILES

.SH ENVIRONMENT

.SH DIAGNOSTICS
Currently there are no error codes.  In future releases, however, we
will be thinking more carefully about error codes and how to report
these errors back to the calling environment.

.SH BUGS
There are likely plenty as this release of xuwc(1) incorporates a new 
API for text corpora.  Bug reports are welcomed, we want to make these
tools as strong as possible.

.SH EXAMPLES

.SS Cisco IOS
.P
.B xuwc \(dq/builtin:file/ios:interface\(dq ./data/test/cisco_ios/router.v1.example 
.br
Count the number of interfaces in version 1 of this router configuration file.  

.P
.B xuwc \(dq/builtin:file/ios:interface/builtin:line\(dq ./data/test/cisco_ios/router.v1.example 
.br
Count the number of lines contained in each interface in the router configuration file.

.P
.B xuwc --count=builtin:line --container=ios:interface \(dq/builtin:file/ios:interface/builtin:line\(dq ./data/test/cisco_ios/router.v1.example 
.br
Count the number of lines contained in each interface in the router configuration file and report
counts relative to interface names.

.P
.B xuwc \(dqbuiltin:file/builtin:line\(dq ./data/test/cisco_ios/router.v1.example 
.br
Count the number of lines per file.

.P
.B xuwc --count=builtin:word --container=builtin:line \(dq/builtin:file/ios:interface/builtin:line\(dq ./data/test/cisco_ios/router.v1.example ./data/test/cisco_ios/router.v2.example | sort -n -k 2 | sort -k 1
.br 
Count the number of words per lines contained in interfaces in both files.

.SS TEI-XML
.P
.B xuwc \(dq/builtin:file/tei:section\(dq ./data/test/tei_xml/section.tei.v1.xml
.br
Count the number of sections per file in this security policy.

.P
.B xuwc --count=tei:paragraph --container=tei:section \(dq/tei:section/tei:paragraph\(dq ./data/test/tei_xml/section.tei.v1.xml
.br
Count the number of paragraphs per section in this security policy.

.P
.B xuwc --count=builtin:word --container=tei:section \(dq/tei:section\(dq ./data/test/tei_xml/section.tei.v1.xml 
.br
Count the number of words per section in this security policy.

.SH AUTHOR
Gabriel A. Weaver <Gabriel.A.Weaver at xutools dot com>

.SH SEE ALSO
.BR wc(1),
.BR xudiff(1),
.BR xupath(1),
.BR xugrep(1)
